# Open Weather Map Config
APIkey = 'YOUR API KEY'


# email stuff
SMTP_SERVER = 'YOUR EMAIL SERVER'
SMTP_PORT = #PUT YOUR EMAIL PORT HERE
SMTP_USERNAME = 'YOUR EMAIL USERNAME'
SMTP_PASSWORD = 'YOUR EMAIL PASSWORD'
EMAIL_FROM = 'YOUR EMAIL ADDRESS'