# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('location', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('forecast_raw', models.TextField(blank=True)),
                ('forecast_clean', models.TextField(blank=True)),
                ('last_updated', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.CharField(max_length=125)),
                ('body', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25, verbose_name='Forecast Nickname')),
                ('locations', models.CharField(max_length=125, verbose_name='Forecast Locations')),
                ('timezone', models.CharField(max_length=25, verbose_name='Forecast Timezone')),
                ('start_time', models.PositiveSmallIntegerField(verbose_name='Forecast Start Time')),
                ('end_time', models.PositiveSmallIntegerField(verbose_name='Forecast End Time')),
                ('alerts', models.CharField(max_length=125, verbose_name='Forecast Alerts')),
                ('days_in_forecast', models.PositiveSmallIntegerField(verbose_name='Number of Days in Forecast')),
                ('last_updated', models.CharField(blank=True, max_length=25, verbose_name='Last Time Forecast Was Run')),
            ],
        ),
    ]
