# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastprofile',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecastemail',
            name='profile',
            field=models.ForeignKey(on_delete=models.SET('DELETED PROFILE'), to='forecasts.ForecastProfile'),
        ),
        migrations.AddField(
            model_name='forecastemail',
            name='recipient',
            field=models.ForeignKey(on_delete=models.SET('DELETED USER'), to=settings.AUTH_USER_MODEL),
        ),
    ]
